optimised day 29
Arejay23/Hackerrank pull request #9
Opened 2020-10-03 07:50 UTC by exilednick

The initial complexity was O(N^2) for each test case.
I optimised it to O(1) for each test case.
[https://drive.google.com/file/d/17lSvflmEsjuir19-exRoN5G9m7U25SeI/view?usp=sharing](url)

2020-10-03 07:57 UTC, Arejay23 requested changes
Not able to access drive link maybe it is private.
Please check.

2020-10-03 07:57 UTC, Arejay23 commented on 30 days of code/Day 29- Bitwise AND/solution.cpp
> +		cin>>n>>K;
Varibale name not correct for K

2020-10-03 08:05 UTC, exilednick commented
![Screenshot from 2020-10-03 12-54-45](https://user-images.githubusercontent.com/28205051/94986531-2d0fe780-057d-11eb-864d-aa5e9c25e030.png)

Made the changes. The link is public but idk why not working, anyways I added the screenshot.

2020-10-04 10:13 UTC, Arejay23 requested changes
![image](https://user-images.githubusercontent.com/25845506/95012680-26a26e00-0658-11eb-811f-576e3d46ea03.png)



I tried to run the same code but it is failing for some sample cases please check

2020-10-06 12:02 UTC, exilednick commented
I updated it. There was a missing bracket

2020-10-07 03:16 UTC, Arejay23 approved these changes

2020-10-07 03:16 UTC, merged